export const USER_ENTER_ROOM = "USER_ENTER_TO_ROOM";
export const USER_LEAVE_ROOM = "USER_ENTER_TO_ROOM";
export const PLAYERS_LIST_IN_ROOM = "PLAYERS_LIST_IN_ROOM";
export const NEW_MESSAGE = "NEW_MESSAGE";
